### ISSUE TITLE
Research available LinkedIn fields

### ISSUE THREAD

**Issue by LegMuscleCramp** [D-Nguyen88/Fall-2018---4350---Software-Engineering#17]

**Comment by D-Nguyen88** [comment]
Linkedin has 3 tier of field that the API can request from. 
- Member profile fields
    - [Basic Profile Fields](https://developer.linkedin.com/docs/fields/basic-profile)
    - [Location Fields](https://developer.linkedin.com/docs/fields/location)
    - [Position Fields](https://developer.linkedin.com/docs/fields/positions)

- Company profile fields ( for company to use
- Member profile fields available to Apply with LinkedIn developers

Basic is what anyone can get, however basic does not have all the field we need for this project.
Member profile fields is what we need because it contain the full profile of the account.
We would need an access token to get the data from linkedin

[Different fields ](https://developer.linkedin.com/docs/fields)
